name: Docs
on: [pull_request]

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Update packages
        run: sudo apt update
      - name: Setup Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: pip install .
      - uses: ammaraskar/sphinx-action@master
        with:
          build-command: "make html" 
          docs-folder: "docs/"
      - name: Commit documentation changes
        run: |
          git clone https://github.com/hmccarty/pytact.git --branch gh-pages --single-branch gh-pages
          ls
          cp -r ./build/html/* gh-pages/docs
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}