name: Unit tests
on: [push, pull_request]

jobs:
  mypy:
  runs-on: ubuntu-20.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update packages
      sudo apt-get update
    - name: Setup Python3.8
      with:
        python-version: 3.8
    - name: Install
      run: pip install .
    - name: Run mypy
      run: mypy .