name: Unit tests
on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt update
      - name: Setup Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install
        run: pip install -e '.[testing]'
      - name: Run mypy
        run: mypy .